AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an SNS Topic and Subscriptions

Parameters:

  TopicName:
    Type: String
    Description: AWS-ECR

  EndPoint:
    Type: String
    Description: email of the user

  Name:
    Type: String
    Description: Name of the SNS subscription

  component:
    Type: String
    Description: Used for Billing and tracking purposes
  
  DisplayName:
    Type: String
    Description: Display Name of the SNS Topic

Resources:
  
  MySNSTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: !Ref EndPoint
          Protocol: "email"
      DisplayName: !Ref DisplayName

      Tags: 
        - Key: Name
          Value: !Ref Name
        - Key: component
          Value: !Ref component
      TopicName: !Ref TopicName     

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument: 
        Id: SNSTopicPolicy
        Version: '2012-10-17'
        Statement:
        - Sid : SNSTopicPolicy
          Action: 
          - sns:Subscribe
          - sns:Publish
          Effect: Allow
          Principal:
            AWS: 'arn:aws:iam::847370586410:role/JD-AppModernization-SME-Role'
          Resource: !Ref MySNSTopic            
      Topics: 
      - !Ref MySNSTopic      
